### ISSUE TITLE
Default Configuration File

### ISSUE THREAD

**Issue by varunagrawal** [gt-sse-center/RepoAuditor#132]
## Is your feature request related to a problem? Please describe.
Now that RepoAuditor supports passing in a configuration file, it would be helpful to have a default one available for pedagogical purposes.

## Describe the solution you'd like
Create a sample `default_config.yaml` which has sensible defaults for new users.

## Describe alternatives you've considered
Users pass in the various flags manually.

**Comment by mtanneau** [comment]
Do we have a documentation of all possible options that can be passed in the config file and how to pass them?

**Comment by mtanneau** [comment]
I find the current syntax of the config file confusing. Here is an excerpt from #134:

```yaml
GitHub-AutoMerge-false: false
GitHub-DefaultBranch-value: "main"
GitHub-DeleteHeadBranches-false: false
GitHub-Description-allow-empty: false
GitHub-DependabotSecurityUpdates-false: false
GitHub-License-value: "MIT License"
GitHub-MergeCommit-false: false
GitHub-MergeCommitMessage-value: "BLANK"
GitHub-Private-true: false
```

The part that is most confusing to me is that suffix `-false` / `-true` / `-value` etc. in the option name.
It's especially confusing for me to read `GitHub-Private-true: false`: I see a "true" and then a "false".



My preferred syntax would have been something like the following:
```yaml
GitHub-AutoMerge: false
GitHub-DefaultBranch: "main"
GitHub-DeleteHeadBranches: false
GitHub-Description-allow-empty: false
GitHub-DependabotSecurityUpdates: false
GitHub-License: "MIT License"
GitHub-MergeCommit: false
GitHub-MergeCommitMessage: "BLANK"
GitHub-Private: false
```
