### ISSUE TITLE
Update Config File Syntax

### ISSUE THREAD

**Issue by varunagrawal** [gt-sse-center/RepoAuditor#149]
Courtesy of @mtanneau 

The current syntax of the config file is confusing. Here is an excerpt from #134:

```yaml
GitHub-AutoMerge-false: false
GitHub-DefaultBranch-value: "main"
GitHub-DeleteHeadBranches-false: false
GitHub-Description-allow-empty: false
GitHub-DependabotSecurityUpdates-false: false
GitHub-License-value: "MIT License"
GitHub-MergeCommit-false: false
GitHub-MergeCommitMessage-value: "BLANK"
GitHub-Private-true: false
```

The part that is most confusing is the suffix `-false` / `-true` / `-value` etc. in the option name.
It's especially confusing to read `GitHub-Private-true: false`: we see a "true" and then a "false".

The preferred syntax would be something like the following:
```yaml
GitHub-AutoMerge: false
GitHub-DefaultBranch: "main"
GitHub-DeleteHeadBranches: false
GitHub-Description-allow-empty: false
GitHub-DependabotSecurityUpdates: false
GitHub-License: "MIT License"
GitHub-MergeCommit: false
GitHub-MergeCommitMessage: "BLANK"
GitHub-Private: false
```
